/* SPDX-License-Identifier: GPL-2.0-or-later */

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[0] = LAYOUT(

		KC_INS,
		KC_TRNS,
		KC_E,
		KC_W,    KC_R,    KC_T,
		KC_Q,
		KC_D,
		KC_S,    KC_F,    KC_G,
		KC_A,
		KC_C,
		KC_X,    KC_V,    KC_B,
		KC_Z,
		KC_LSFT, KC_TRNS, KC_SPC,
		MO(0),   MO(1),   MO(2),   MO(3),   MO(4),
		KC_I,
		KC_Y,    KC_U,    KC_O,
		KC_P,
		KC_K,
		KC_H,    KC_J,    KC_L,
		KC_QUOT,
		KC_COMM,
		KC_N,    KC_M,    KC_DOT,
		KC_SLSH,
		KC_TRNS, KC_ENT,  KC_BSPC
	),

	[1] = LAYOUT(

		KC_TRNS,
		KC_TRNS,
		KC_TAB,
		KC_GRV,  KC_CAPS, KC_SCLN,
		KC_ESC,
		KC_F3,
		KC_F2,   KC_F4,   KC_F5,
		KC_F1,
		KC_3,
		KC_2,    KC_4,    KC_5,
		KC_1,
		KC_LCTL, KC_TRNS, KC_LSFT,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_F12,
		KC_BSLS, KC_F11,  KC_MINS,
		KC_EQL,
		KC_F8,
		KC_F6,   KC_F7,   KC_F9,
		KC_F10,
		KC_8,
		KC_6,    KC_7,    KC_9,
		KC_0,
		KC_TRNS, KC_RALT, KC_RGUI
	),

	[2] = LAYOUT(

		KC_MUTE,
		KC_TRNS,
		KC_INS,
		KC_SCRL, KC_HOME, KC_PGUP,
		KC_PSCR,
		KC_DEL,
		KC_END,  KC_UP,   KC_PGDN,
		KC_PAUS,
		KC_LEFT,
		KC_TRNS, KC_DOWN, KC_RGHT,
		KC_NUM,
		KC_BSPC, KC_TRNS, KC_ENT,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_P9,
		KC_P7,   KC_P8,   KC_PSLS,
		KC_PAST,
		KC_P6,
		KC_P4,   KC_P5,   KC_PMNS,
		KC_PPLS,
		KC_P3,
		KC_P1,   KC_P2,   KC_PCMM,
		KC_PEQL,
		KC_TRNS, KC_P0,   KC_PDOT
	),

	[3] = LAYOUT(

		KC_NUM,
		KC_TRNS,
		KC_W,
		KC_Q,    KC_E,    KC_R,
		KC_ESC,
		KC_S,
		KC_A,    KC_D,    KC_F,
		KC_TAB,
		KC_X,
		KC_Z,    KC_C,    KC_V,
		KC_LSFT,
		KC_LCTL, KC_TRNS, KC_SPC,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_P9,
		KC_P7,   KC_P8,   KC_PSLS,
		KC_PAST,
		KC_P6,
		KC_P4,   KC_P5,   KC_PMNS,
		KC_PPLS,
		KC_P3,
		KC_P1,   KC_P2,   KC_PCMM,
		KC_PEQL,
		KC_TRNS, KC_P0,   KC_PDOT
	),

	[4] = LAYOUT(

		XXXXXXX,
		KC_TRNS,
		XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX,
		XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX,
		XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX,
		XXXXXXX, KC_TRNS, XXXXXXX,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX,
		XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX,
		XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX,
		KC_TRNS, XXXXXXX, XXXXXXX
	),

	[5] = LAYOUT(

		KC_TRNS,
		KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_LCTL, KC_TRNS, KC_LSFT,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_RALT, KC_RGUI
	),

};


/* `ENCODER_MAP_ENABLE = yes` must be added to the rules.mk at the KEYMAP level. See QMK docs. */
/* Remove the following code if you do not enable it in your keymap (e.g. default keymap). */
#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
	[0] = { ENCODER_CCW_CW(KC_LEFT, KC_RGHT), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
	[1] = { ENCODER_CCW_CW(KC_DOWN, KC_UP), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
	[2] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
	[3] = { ENCODER_CCW_CW(KC_DOWN, KC_UP), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
	[4] = { ENCODER_CCW_CW(XXXXXXX, XXXXXXX), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
	[5] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
};
#endif
